### ISSUE TITLE
where is this lon / lat?

### ISSUE THREAD

**Issue by hkruit** [Montapacking/magento-monta-checkout#11]
https://github.com/Montapacking/magento-monta-checkout/blob/15242d75f383731adc7783a71dabdbc7f3267095/Api/Objects/Address.php#L98

what happens when you default to 0,0 lon/lat ?https://www.google.nl/maps/place/0%C2%B000'00.0%22N+0%C2%B000'00.0%22E/@0,-0.0021887,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0

**Comment by andrevlot** [comment]
when 0 0 there are no pick up points showed, and this will be hided
