### ISSUE TITLE
api failure

### ISSUE THREAD

**Issue by hkruit** [Montapacking/magento-monta-checkout#14]
what happens when the API borks? 
https://github.com/Montapacking/magento-monta-checkout/blob/15242d75f383731adc7783a71dabdbc7f3267095/Controller/AbstractDeliveryOptions.php#L104 

Please add some tests to make sure the API is returning something you can work with

**Comment by andrevlot** [comment]
When the default API has no connection, the default price in the admin is shown. And no API will be used, so orders can proceed with their order
