### ISSUE TITLE
css files to less files

### ISSUE THREAD

**Issue by hkruit** [Montapacking/magento-monta-checkout#23]
please transfer the css files to less files and don't include them in the header, instead let it be part of the overall stylesheet

**Comment by andrevlot** [comment]
fixed in upcoming commit, css stays in head. see official documentation:
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/css-themes.html

**Comment by hkruit** [comment]
You could create a file view/web/css/source/_module.less that way the styling for your module will be merged / minified with the rest of magento modules.
