### ISSUE TITLE
$origins is always an array.

### ISSUE THREAD

**Issue by hkruit** [Montapacking/magento-monta-checkout#3]
https://github.com/Montapacking/magento-monta-checkout/blob/15242d75f383731adc7783a71dabdbc7f3267095/Api/MontapackingShipping.php#L218

you could also use 
if (isset($result->origins)) {
    $origins = is_array($result->Origins) ? $result->Origins : [$result->Origins];
} 
to make sure $origins is always an array.

**Comment by andrevlot** [comment]
fixed in upcoming commit
