### ISSUE TITLE
Sleeps in API call

### ISSUE THREAD

**Issue by AngelsDustz** [Montapacking/magento-monta-checkout#31]
Right now the module will sleep when no result is returned, and not once. Not twice, but three time will it sleep with an increment leaving the request hang for **at least 18 seconds**.

When using another third party integration having an 18 second delay on a API call is disastrous. With a maximum execution time of 30 second this could also easily result in a E_FATAL or E_ERROR.

See https://github.com/Montapacking/magento-monta-checkout/blob/6cdfd57932d23f46b0325d9858fbf31e3a280aba/Api/MontapackingShipping.php#L450 and below.

**Comment by jvdsmonta** [comment]
We agree to reduce to a single retry after 2 seconds.

**Comment by andrevlot** [comment]
In last commit we changed the requests to:  1 retry after 2 seconds timeout, retry will be done after 1 second
