### ISSUE TITLE
Front-end breaks when no API results

### ISSUE THREAD

**Issue by AngelsDustz** [Montapacking/magento-monta-checkout#32]
When the delivery method API call returns 0 results the front-end tries to iterate over it causing a JavaScript error and locking up the checkout process.

![Screenshot from 2021-06-15 10-54-55](https://user-images.githubusercontent.com/4640484/122023849-37e77100-cdc8-11eb-9b4d-711c5a267f71.png)

**Comment by andrevlot** [comment]
I cannot reproduce this. Can you explain this how to reproduce?

**Comment by AngelsDustz** [comment]
When the API for delivery methods gives no results, this is what happens. Maybe you can try with an API with no shipping methods or pick-up points.

**Comment by AngelsDustz** [comment]
Checked with a known-good API with methods, still the same error happens.
