### ISSUE TITLE
Slow delivery format code

### ISSUE THREAD

**Issue by AngelsDustz** [Montapacking/magento-monta-checkout#33]
In the delivery format code, it reiterates over the same frame 3 times. In these iterations we iterate over all options. This has a time complexity of `3n^2`. A simple refactor should resolve this.

See:

https://github.com/Montapacking/magento-monta-checkout/blob/6cdfd57932d23f46b0325d9858fbf31e3a280aba/Controller/DeliveryOptions/Delivery.php#L124

https://github.com/Montapacking/magento-monta-checkout/blob/6cdfd57932d23f46b0325d9858fbf31e3a280aba/Controller/DeliveryOptions/Delivery.php#L174

https://github.com/Montapacking/magento-monta-checkout/blob/6cdfd57932d23f46b0325d9858fbf31e3a280aba/Controller/DeliveryOptions/Delivery.php#L220

**Comment by andrevlot** [comment]
In the last commit, I've refactorerd this code
