### ISSUE TITLE
Web ui issues

### ISSUE THREAD

**Issue by leonhelmus** [Montapacking/magento-monta-checkout#46]
After installing the latest commit hash using composer:
"montapacking/montacheckout": "dev-master#d1f16fbc393273a03483f8b616445fbc8e2360e8 as 1.0.19"
Magento version: 2.4.4-p1
PHP 8.1

We experienced some issues with the latest addition named delivery days especially with web UI:

1. The carousel behaves weird after clicking multiply times on arrows. See screenshot: ![image](https://user-images.githubusercontent.com/18070887/217286095-8249fb54-5b85-4cc8-a677-5d0c395c0271.png)
2. On mobile the carousel scrolls too far and too fast so if customer wants to select next day after visible one it is impossible. Like on video, it is not possible to select 21st. See screenshot: ![image](https://user-images.githubusercontent.com/18070887/217286267-f0ae6ccc-91f6-424e-b10d-b356402f9134.png)
3. If I select a date and delivery method, then I select another shipping address, datepicker is not shown again. 
![image](https://user-images.githubusercontent.com/18070887/217286777-d934f734-a397-4140-9492-f6c54fb362df.png) 
4. I thought maybe it can be disabled in admin somewhere, and I see that it can be in admin > stores > configurations > sales > shipping methods > Monta > 'Disable delivery days'. But these settings probably disable something else as well, like delivery time near the delivery options. So it is not possible just disable new datepicker functionality, I assume.
When datepicker is not shown in checkout (see point 2) or disabled, it has a side effect that delivery time and some links are not present as well. See screenshot below:
![image](https://user-images.githubusercontent.com/18070887/217287341-66b5c1bf-7825-49b0-844f-ef3a7a955a38.png)

We would really like to update this module, but at the moment it's not possible because of the ui issues. This prevents customers from doing their orders.

Please let me know if you need more info.

**Comment by leonhelmus** [comment]
@RemcovdMonta For now it looks a lot better! I will first need to let it be tested by qa to be sure. But overall it looks promising.

**Comment by leonhelmus** [comment]
@RemcovdMonta Some of the functionality now has changed this prevented us from upgrading it, since we created custom functionality based on it. This function does not exist anymore. Which was used:
\Montapacking\MontaCheckout\Controller\DeliveryOptions\Delivery::formatShippingOptions 

For now we will wait before we upgrade. Can't guarantee that everything is resolved.. :(.

**Comment by RemcovdMonta** [comment]
That function has been migrated to a different class. The [DeliveryHelper class](https://github.com/Montapacking/magento-monta-checkout/blob/838dc81b9c7b7ee5de1d856e826a6c29c33223d2/Helper/DeliveryHelper.php), this function works the same way as it did in earlier builds.

**Comment by leonhelmus** [comment]
@RemcovdMonta ah alright, than we don't have to do any migrations.

**Comment by leonhelmus** [comment]
@RemcovdMonta It seems because you now use  slider.scrollTo it did not work, because we loaded prototype still. After removing scrollTo it does work :)
