### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by HyperC** [Montapacking/magento-monta-checkout#56]
The module is not compatible with php 8.2. For example:

Dynamically declared properties:
montapacking/montacheckout/Api/Objects/ShippingOption.php:251 ($this->isSustainable)
montapacking/montacheckout/Helper/DeliveryHelper.php:88 ($frame->code_desc)
etc.

**Comment by RemcovdMonta** [comment]
Should be fixed in v1.0.28, thanks!
