### ISSUE TITLE
move to top of method

### ISSUE THREAD

**Issue by hkruit** [Montapacking/magento-monta-checkout#7]
https://github.com/Montapacking/magento-monta-checkout/blob/15242d75f383731adc7783a71dabdbc7f3267095/Api/MontapackingShipping.php#L381
I would move this check to the top of the method.
        if (trim($this->address->postalcode) && (trim($this->address->housenumber) || trim($this->address->street))) {
}
and if these are empty return an empty array.
There seems to no need to further do anything in the method.

**Comment by andrevlot** [comment]
fixed in upcoming commit
